name: CI/CD Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check Node and NPM
        run: |
          node -v
          npm -v

        
      - name: Install dependencies and build using npm
        run: "/home/github-runner-if/.asdf/shims/npm run deno-deploy"

      - name: Archive build artifacts
        run: |
          tar -czvf intellectualfrontiers.tar.gz deno-deploy

      - name: Copy build artifacts to the production server
        run: |
          scp -P22 -o StrictHostKeyChecking=no intellectualfrontiers.tar.gz "${{ secrets.PRODUCTION_DEPLOYMENT_USER }}@${{ secrets.PRODUCTION_DEPLOYMENT_SERVER_IP }}:"

      - name: Deploy to production server
        run: |
          ssh -p22 -o StrictHostKeyChecking=no -t ${{ secrets.PRODUCTION_DEPLOYMENT_USER }}@${{ secrets.PRODUCTION_DEPLOYMENT_SERVER_IP }} "bash -i intellectual-frontiers.sh"
