name: CI/CD Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: intellectual-frontiers

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: |
          sudo apt update
          sudo apt install openssh-client -y

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY_PROD }}" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Install dependencies and build using npm
        run: "npm run deno-deploy"

      - name: Archive build artifacts
        run: |
          tar -czvf intellectualfrontiers.tar.gz deno-deploy

      - name: Copy build artifacts to the production server
        run: |
          scp -P22 -o StrictHostKeyChecking=no intellectualfrontiers.tar.gz "${{ secrets.PRODUCTION_DEPLOYMENT_USER }}@${{ secrets.PRODUCTION_DEPLOYMENT_SERVER_IP }}:"

      - name: Deploy to production server
        run: |
          ssh -p22 -o StrictHostKeyChecking=no -t ${{ secrets.PRODUCTION_DEPLOYMENT_USER }}@${{ secrets.PRODUCTION_DEPLOYMENT_SERVER_IP }} "bash -i intellectual-frontiers.sh"
